class_name WorldBuilder
extends RefCounted
## Creates the world nodes of main.gd (sky, audio, ground, scenery, critters, course, slingshot, alien, camera,
## effects...) as children of main, in drawing order. New world decorations are added here, not in main.gd.


static func build(main: Node) -> void:
	main.background = SkyBackground.new()  # must be the first child
	main.add_child(main.background)
	main.audio = AudioManager.new()
	main.add_child(main.audio)
	main.apply_settings()
	main.fader = Fader.new()
	main.add_child(main.fader)
	main.world_view = WorldView.new()
	main.add_child(main.world_view)
	main.scenery = Scenery.new()
	main.add_child(main.scenery)
	main.scenery.build(Scenery.SEED, Scenery.LENGTH)
	main.critters = Critters.new()
	main.add_child(main.critters)
	main.critters.build(Critters.SEED, Balance.COURSE_LENGTH)
	main.flowers = Flowers.new()
	main.add_child(main.flowers)
	main.cows = Cows.new()
	main.add_child(main.cows)
	main.kites = Kites.new()
	main.add_child(main.kites)
	var sock := WindSock.new()
	main.add_child(sock)
	main.add_child(SkyBalloons.new())
	main.zone_marker = ZoneMarker.new()
	main.add_child(main.zone_marker)
	var boss_view := BossView.new()
	main.add_child(boss_view)
	main.birds = Birds.new()
	main.add_child(main.birds)
	main.ufo = Ufo.new()
	main.add_child(main.ufo)
	main.course_view = CourseView.new()
	main.add_child(main.course_view)
	main.balloon_view = BalloonView.new()
	main.add_child(main.balloon_view)
	main.slingshot = Slingshot.new()
	main.add_child(main.slingshot)
	main.trajectory = TrajectoryPreview.new()
	main.add_child(main.trajectory)
	main.ghost = GhostPath.new()
	main.add_child(main.ghost)
	main.trail = Trail.new()
	main.add_child(main.trail)
	main.shadow = GroundShadow.new()
	main.add_child(main.shadow)
	main.projectile_view = ProjectileView.new()
	main.add_child(main.projectile_view)
	main.camera = CameraRig.new()
	main.add_child(main.camera)
	main.camera.shake_enabled = main.progress.shake_on
	main.popups = Node2D.new()
	main.add_child(main.popups)
	main.effects = Effects.new()
	main.add_child(main.effects)
	main.feedback = Feedback.new()
	main.add_child(main.feedback)
	main.feedback.boss_view = boss_view
	main.feedback.flowers = main.flowers
	main.feedback.cows = main.cows
	main.weather_fx = WeatherFx.new()
	main.add_child(main.weather_fx)
	main.weather_fx.windsock = sock
